[package]
name = "blockchainai-contracts"
version = "0.1.0"
edition = "2021"

[lib]
name = "blockchainai_contracts"
path = "src/lib.rs"

[dependencies]
multiversx-sc = "0.46.1"
multiversx-sc-derive = "0.46.1"
multiversx-sc-modules = "0.46.1"

[dev-dependencies]
multiversx-sc-scenario = "0.46.1"